name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  html-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install html-validator-cli
        run: npm install -g html-validator-cli

      - name: Validate HTML files
        run: |
          echo "Buscando archivos HTML..."
          HTML_FILES=$(find . -type f -name "*.html")
          if [ -z "$HTML_FILES" ]; then
            echo "No se encontraron archivos HTML para validar."
            exit 0
          fi

          echo "Archivos encontrados:"
          echo "$HTML_FILES"

          for file in $HTML_FILES; do
            echo "Validando: $file"
            html-validator --file="$file" --format=gnu || exit_code=$?
          done

          if [ "$exit_code" != "" ]; then
            echo "Se encontraron errores de validación HTML."
            exit 1
          else
            echo "Todos los archivos HTML son válidos ✅"
          fi
