name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  html-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install html-validator-cli
        run: npm install -g html-validator-cli

      - name: Run HTML validation
        run: |
          find . -name "*.html" -print0 | xargs -0 -n1 html-validator --format=gnu

